# US - Baby Names

### Introduction:

We are going to use a subset of [US Baby Names](https://www.kaggle.com/kaggle/us-baby-names) from Kaggle.  
In the file it will be names from 2004 until 2014


### Step 1. Import the necessary libraries

In [ ]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/thieu1995/csv-files/main/data/pandas/US_Baby_Names_right.csv).

### Step 3. Assign it to a variable called baby_names.

In [ ]:
baby_names = pd.read_csv('https://raw.githubusercontent.com/thieu1995/csv-files/main/data/pandas/US_Baby_Names_right.csv')

### Step 4. See the first 10 entries

In [ ]:
display(baby_names.head(10))

   Unnamed: 0     Id      Name  Year Gender State  Count
0       11349  11350      Emma  2004      F    AK     62
1       11350  11351   Madison  2004      F    AK     48
2       11351  11352    Hannah  2004      F    AK     46
3       11352  11353     Grace  2004      F    AK     44
4       11353  11354     Emily  2004      F    AK     41
5       11354  11355   Abigail  2004      F    AK     37
6       11355  11356    Olivia  2004      F    AK     33
7       11356  11357  Isabella  2004      F    AK     30
8       11357  11358    Alyssa  2004      F    AK     29
9       11358  11359    Sophia  2004      F    AK     28

### Step 5. Delete the column 'Unnamed: 0' and 'Id'

In [ ]:
baby_names = baby_names.drop(['Unnamed: 0', 'Id'], axis=1)
display(baby_names.head())

      Name  Year Gender State  Count
0     Emma  2004      F    AK     62
1  Madison  2004      F    AK     48
2   Hannah  2004      F    AK     46
3    Grace  2004      F    AK     44
4    Emily  2004      F    AK     41

### Step 6. Is there more male or female names in the dataset?

In [ ]:
gender_counts = baby_names['Gender'].value_counts()
display(gender_counts)

Gender
F    558846
M    457549
Name: count, dtype: int64

### Step 7. Group the dataset by name and assign to names

In [ ]:
names = baby_names.groupby('Name').sum(numeric_only=True)
display(names.head())

           Year  Count
Name
Aaban      4027     12
Aadan      8039     23
Aadarsh    2009      5
Aaden    393963   3426
Aadhav     2014      6

### Step 8. How many different names exist in the dataset?

In [ ]:
display(len(names))

17632

### Step 9. What is the name with most occurrences?

In [ ]:
most_common_name = names.sort_values(by='Count', ascending=False).head(1)
display(most_common_name)

          Year   Count
Name
Jacob  1141099  242874

### Step 10. How many different names have the least occurrences?

In [ ]:
least_common_count = names.sort_values(by='Count', ascending=True).head(1)['Count'].iloc[0]
least_common_names_count = names[names['Count'] == least_common_count].shape[0]
display(least_common_names_count)

2578

### Step 11. What is the median name occurrence?

In [ ]:
median_occurrence = names['Count'].median()
display(median_occurrence)

49.0

### Step 12. What is the standard deviation of names?

In [ ]:
std_occurrence = names['Count'].std()
display(std_occurrence)

11006.069467891111

### Step 13. Get a summary with the mean, min, max, std and quartiles.

In [ ]:
display(names['Count'].describe())

count     17632.000000
mean       2008.932169
std       11006.069468
min           5.000000
25%          11.000000
50%          49.000000
75%         337.000000
max      242874.000000
Name: Count, dtype: float64